
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URI;
import java.util.StringTokenizer;
import javax.swing.Action;
import javax.swing.ImageIcon;


public class Movie_details extends javax.swing.JFrame {

    int movie_id;
    
    public Movie_details(int id) {
        initComponents();
        setSize(700, 500);
        moviename.setEnabled(false);
        castlb.setEnabled(false);
        movie_id = id;
        loadmovie();
           
        
    }
    
    void loadmovie()
    {
       String ans = myClient.moviedetail(movie_id);
       
        StringTokenizer st = new StringTokenizer(ans,"$");
        
        String name = st.nextToken();
        String cast = st.nextToken();
        String youtube_id = st.nextToken();
        String photo = st.nextToken();
        String movie_link = st.nextToken();
        
        ImageIcon ic = new ImageIcon(photo);
       Image img = ic.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon ic1 = new ImageIcon(img);
       photolb.setIcon(ic1);
       
       moviename.setText(name);
       castlb.setText(cast);
       
       trailerbt.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               try {
                   
            
             URI uri = new URI("https://www.youtube.com/watch?v="+youtube_id);
             
                   Desktop d = Desktop.getDesktop();
                   
                   d.browse(uri);
               
                  } 
               catch (Exception ex) 
               {
               }
           }
       });
    
       bt.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               try
               {
          File f = new File(movie_link);
          
          Desktop d = Desktop.getDesktop();
          
          d.open(f);
               }
               catch(Exception ex)
               {
                   ex.printStackTrace();
               }
           }
       });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photolb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        moviename = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        castlb = new javax.swing.JTextField();
        bt = new javax.swing.JButton();
        trailerbt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(photolb);
        photolb.setBounds(0, 0, 320, 440);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Movie name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 50, 140, 30);
        getContentPane().add(moviename);
        moviename.setBounds(350, 90, 280, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Star Cast");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 150, 140, 40);
        getContentPane().add(castlb);
        castlb.setBounds(350, 200, 280, 30);

        bt.setBackground(new java.awt.Color(0, 0, 0));
        bt.setForeground(new java.awt.Color(255, 255, 255));
        bt.setText("Play Movie");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(400, 380, 190, 40);

        trailerbt.setBackground(new java.awt.Color(204, 204, 204));
        trailerbt.setText("Play Trailer");
        trailerbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trailerbtActionPerformed(evt);
            }
        });
        getContentPane().add(trailerbt);
        trailerbt.setBounds(400, 273, 190, 40);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 650, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btActionPerformed

    private void trailerbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trailerbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trailerbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movie_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movie_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movie_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movie_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movie_details(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JTextField castlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField moviename;
    private javax.swing.JLabel photolb;
    private javax.swing.JButton trailerbt;
    // End of variables declaration//GEN-END:variables
}
