
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author macbookair
 */
public class search_demo extends javax.swing.JFrame {

    /**
     * Creates new form search_demo
     */
    public search_demo() {
        initComponents();
    }
 void loadmovies()
    {
        mainpanel.removeAll();
        mainpanel.repaint();
        if(!tf.getText().equals(""))
        {
        String ans = myClient.search(tf.getText());
        
        StringTokenizer st = new StringTokenizer(ans,";;");
        int n = st.countTokens();
        
        JButton arr[] = new JButton[n];
        
        int x=10,y=10;
        
        for (int i = 0; i < n; i++) 
        {
            String row = st.nextToken();
            StringTokenizer st1 = new StringTokenizer(row,"$");
            
            int id = Integer.parseInt(st1.nextToken());
            String name = st1.nextToken();
            String photo = st1.nextToken();
            
            
            arr[i] = new JButton(name);
            
            
            arr[i].setBounds(x, y, 250, 80);
            
          ImageIcon ic = new ImageIcon(photo);
          
          Image img = ic.getImage().getScaledInstance(100, 75, Image.SCALE_SMOOTH);
          
          ImageIcon ic1 = new ImageIcon(img);
          
          arr[i].setIcon(ic1);
         
          arr[i].addActionListener(new ActionListener()
          {
          public void actionPerformed(ActionEvent e)
          {
            Movie_details obj = new Movie_details(id); 
            obj.setVisible(true);
          }
          
          }
          );
          
          
          mainpanel.add(arr[i]);
          mainpanel.repaint();
          
          if(x<=520)
          {
              x= x+260;
          }
         else
          {
              x=10;
              y=y+50;
          }
        } 
         mainpanel.setPreferredSize(new Dimension(530, n*50));
        }
        else
        {
            mainpanel.removeAll();
            mainpanel.repaint();
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tf.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfCaretUpdate(evt);
            }
        });
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });
        getContentPane().add(tf);
        tf.setBounds(26, 47, 420, 40);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 2, 2);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(mainpanel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 100, 470, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    private void tfCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfCaretUpdate
       loadmovies();
    }//GEN-LAST:event_tfCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
